# Syntax
# ----------------------------------------------------
# Syntax
"function"               = "green"
"constructor"            = "green"

"type"                   = "cyan"
"namespace"              = "cyan"
"module"                 = "cyan"

"constant"               = "blue"

"variable"               = "warm-white"

"attribute"              = "yellow"
"variable.parameter"     = "yellow"
"variable.other.member"  = "yellow"
"type.parameter"         = "yellow"

"keyword"                = "orange"
"variable.builtin"       = "orange"
"label"                  = "orange"
"tag"                    = "orange"
"operator"               = "orange"
"special"                = "orange" # fuzzy highlight

"punctuation.special"    = "orange"
"string.special"         = "orange"
"string.regexp"          = "orange"

"string"                 = "dark-cyan"

"punctuation"            = "punct"

"comment"                = "comment"

# UI, markup, other non-syntax stuff
# ----------------------------------------------------

"markup.heading.marker" = { fg = "orange", modifiers = ["bold"] }
"markup.heading" = { fg = "white", modifiers = ["bold"] }
"markup.list" = "orange"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "yellow", modifiers = ["italic"] }
"markup.link.url" = "dark-cyan"
"markup.link.text" = "cyan"
"markup.quote" = "green"
"markup.raw" = "green"

"diff.plus" = "green"
"diff.delta" = "blue"
"diff.minus" = "red"

# User Interface
# --------------
"ui.background" = { fg = "dark-fg", bg = "dark-bg" }

"ui.linenr" = { fg = "dark-fg" }
"ui.linenr.selected" = "saturated-yellow"

"ui.statusline" = { fg = "light-fg", bg = "light-bg" }
"ui.statusline.inactive" = { fg = "dark-fg", bg = "light-bg" }
"ui.statusline.insert" = { fg = "black", bg = "green" }
"ui.statusline.select" = { fg = "black", bg = "yellow" }
"ui.statusline.normal" = { fg = "black", bg = "orange" }

"ui.bufferline.background" = { bg = "dark-bg" }
"ui.bufferline" = { fg = "light-fg", bg = "light-bg" }
"ui.bufferline.active" = { fg = "white", bg = "dark-fg" }

# hover, whichkey
"ui.popup" = { fg = "dark-fg", bg = "light-bg" }
# menus
"ui.menu" = { fg = "light-fg", bg = "light-bg" }
"ui.menu.selected" = { fg = "white", bg = "dark-fg", modifiers = ["bold"] }
# command description
"ui.help" = { fg = "light-fg", bg = "light-bg" }
# splits
"ui.window" = { fg = "light-bg", bg = "dark-bg" }

# base text (including markdown)
"ui.text" = "light-fg"
# picker hl
"ui.text.focus" = { fg = "white", bg = "light-bg", modifiers = ["bold"] }

"ui.virtual" = "dark-fg"
"ui.virtual.ruler" = { bg = "medium-bg" }
"ui.virtual.indent-guide" = "indent"

"ui.cursorline.primary" = { bg = "black" }
"ui.cursorcolumn.primary" = { bg = "black" }

# selections & cursors
"ui.selection.primary" = { fg = "white", bg = "dark-blue" }
"ui.selection" = { fg = "light-fg", bg = "dark-fg" }

"ui.cursor.primary" = { fg = "black", bg = "saturated-yellow" }
"ui.cursor.primary.select" = { fg = "black", bg = "yellow" }
"ui.cursor.primary.insert" = { fg = "black", bg = "green" }
"ui.cursor" = { fg = "black", bg = "light-fg" }
"ui.cursor.match" = { fg = "black", bg = "blue", modifiers = ["bold"] }

"ui.highlight" = { bg = "light-bg" }

"info" = "blue"
"hint" = "blue"
"warning" = "saturated-yellow"
"error" = "red"
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "saturated-yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "blue", style = "curl" } }

[palette]
red        = "#FE5F55"
green      = "#88B830"
yellow     = "#FFDE82"
dark-cyan  = "#54B3A0"
orange     = "#F09038"
cyan       = "#93E6B4"
blue       = "#30B0F0"
warm-white = "#fffdf0"
punct      = "#98A8A0"
comment    = "#929292"

black      = "#1e1e1e"
dark-bg    = "#242424"
medium-bg  = "#2D2D2D"
light-bg   = "#353535"
indent     = "#404040"
dark-fg    = "#616161"
light-fg   = "#fffdf0"
white      = "#fffdf0"  # very bright text

dark-blue         = "#007888"
saturated-yellow  = "#F0B858"

# Preview (syntax colors only)
# ----------------------------------------------------
# https://coolors.co/f09038-ffde82-30b0f0-90e0b0-489888-88b830-fdf6e3-98a8a0
