# Syntax
# ----------------------------------------------------
"function" = "function"
"constructor" = "function"

"type" = "namespace"
"string.special" = "const"
"string.regexp" = "const"
"constant" = "const"

"namespace" = "namespace"
"module" = "namespace"

"variable" = "variable"

"string" = "string"

"attribute" = "attribute"
"variable.parameter" = "attribute"
"variable.other.member" = "attribute"

"keyword" = "keyword"
"variable.builtin" = "keyword"
"label" = "keyword"
"tag" = "keyword"
"operator" = "keyword"

"punctuation" = "punct"
"punctuation.special" = "const"

"comment" = "comment"


# UI, markup, other non-syntax stuff
# ----------------------------------------------------
"special" = "keyword" # fuzzy highlight

"markup.heading.marker" = { fg = "keyword", modifiers = ["bold"] }
"markup.heading" = { fg = "variable", modifiers = ["bold"] }
"markup.list" = "keyword"
"markup.bold" = { fg = "attribute", modifiers = ["bold"] }
"markup.italic" = { fg = "attribute", modifiers = ["italic"] }
"markup.link.url" = "string"
"markup.link.text" = "namespace"
"markup.quote" = "function"
"markup.raw" = "function"

"diff.plus" = "function"
"diff.delta" = "const"
"diff.minus" = "red"

# User Interface
# --------------
"ui.background" = { fg = "dark-fg", bg = "dark-bg" }

"ui.linenr" = { fg = "dark-fg" }
"ui.linenr.selected" = "attention"

"ui.statusline" = { fg = "light-fg", bg = "light-bg" }
"ui.statusline.inactive" = { fg = "dark-fg", bg = "light-bg" }
"ui.statusline.insert" = { fg = "black", bg = "function" }
"ui.statusline.select" = { fg = "black", bg = "attribute" }
"ui.statusline.normal" = { fg = "black", bg = "selection" }

"ui.bufferline.background" = { bg = "dark-bg" }
"ui.bufferline" = { fg = "light-fg", bg = "light-bg" }
"ui.bufferline.active" = { fg = "white", bg = "dark-fg" }

# hover, whichkey
"ui.popup" = { fg = "dark-fg", bg = "light-bg" }
# menus
"ui.menu" = { fg = "light-fg", bg = "light-bg" }
"ui.menu.selected" = { fg = "white", bg = "dark-fg", modifiers = ["bold"] }
# command description
"ui.help" = { fg = "light-fg", bg = "light-bg" }
# splits
"ui.window" = { fg = "light-bg", bg = "dark-bg" }

# base text (including markdown)
"ui.text" = "light-fg"
# picker hl
"ui.text.focus" = { fg = "white", bg = "light-bg", modifiers = ["bold"] }

"ui.virtual" = "dark-fg"
"ui.virtual.ruler" = { bg = "medium-bg" }
"ui.virtual.indent-guide" = "indent"

"ui.cursorline.primary" = { bg = "black" }
"ui.cursorcolumn.primary" = { bg = "black" }

# selections & cursors
"ui.selection.primary" = { fg = "white", bg = "selection" }
"ui.selection" = { fg = "light-fg", bg = "dark-fg" }

"ui.cursor.primary" = { fg = "black", bg = "attention" }
"ui.cursor.primary.select" = { fg = "black", bg = "attribute" }
"ui.cursor.primary.insert" = { fg = "black", bg = "function" }
"ui.cursor" = { fg = "black", bg = "light-fg" }
"ui.cursor.match" = { fg = "black", bg = "selection", modifiers = ["bold"] }

"ui.highlight" = { bg = "light-bg" }

"info" = "const"
"hint" = "const"
"warning" = "attention"
"error" = "red"
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "attention", style = "curl" } }
"diagnostic.info" = { underline = { color = "const", style = "curl" } }
"diagnostic.hint" = { underline = { color = "const", style = "curl" } }

[palette]
# Syntax colors (don't use / use sparingly in the UI)
# ----------------------------------------------------
function   = "#88B830"
namespace  = "#90E0B0"
string     = "#489888"
const      = "#30B0F0"
attribute  = "#FFDE82"
keyword    = "#F09038"
variable   = "#FDF6E3"
punct      = "#98A8A0"
comment    = "#808880"

# UI
# ----------------------------------------------------
# Grays dark to bright
black      = "#1e1e1e"  # black text, cursorline
dark-bg    = "#242424"  # base background
medium-bg  = "#2D2D2D"  # rulers
light-bg   = "#353535"  # menu / popup bg
indent     = "#404040"  # indent
dark-fg    = "#6A6A6A"  # barely legible text
light-fg   = "#E6E6E6"  # normal / bright text
white      = "#FFFFFF"  # very bright text

# colors (non-syntax)
selection  = "#007888"  # text selection
attention  = "#F0B858"  # primary cursor, warnings
red        = "#FE5F55"  # error, deletion

# Preview (syntax colors only)
# ----------------------------------------------------
# https://coolors.co/f09038-ffde82-30b0f0-90e0b0-489888-88b830-fdf6e3-98a8a0
