inherits = "dark"
# Syntax
# ----------------------------------------------------
# Syntax
"function"               = "green"

"type"                   = "cyan"
"constructor"            = "cyan"

"constant"               = "blue"
"constant.numeric"       = "blue"
"constant.builtin"       = "blue"
"constant.character"     = "blue"

"namespace"              = "fg0"
"module"                 = "fg0"
"variable"               = "fg0"
"attribute"              = "fg0"
"variable.parameter"     = "fg0"
"variable.other.member"  = "fg0"

"keyword"                = "orange"
"variable.builtin"       = "orange"
"label"                  = "orange"
"special"                = "orange"
"tag"                    = "orange"

"punctuation"            = "fg1"
"operator"               = "fg1"
"punctuation.bracket"    = "fg1"

"string"                 = "dark-green"

"comment"                = "yellow"

[palette]
red        = "#FE5F55"
green      = "#A1C149"
yellow     = "#F0B858"
blue       = "#30B0F0"
cyan       = "#90E0B0"
orange     = "#F09038"
dark-green = "#50B068"
magenta    = "#F8B5FF"

# fg1        = "#B8B8A0"
# fg2        = "#809088"
# fg0        = "#fcfaea"
