# Syntax
"function"               = "yellow"
"special"                = "blue"

"type"                   = "orange"
"constructor"            = "orange"

"constant.numeric"       = "blue"
"constant.character"     = "blue"
"constant.builtin"       = "blue"
"keyword"                = "blue"
"label"                  = "blue"
"variable.builtin"       = "blue"
"tag"                    = "blue"

"variable"               = "light-cyan"
"constant"               = "light-cyan"
"attribute"              = "light-cyan"
"module"                 = "light-cyan"
"namespace"              = "light-cyan"

"punctuation"            = "fg0"
"operator"               = "fg0"
"punctuation.bracket"    = "fg0"

"string"                 = "green"

"comment"                = "fg1"

"markup.heading"         = { fg = "fg0", modifiers = ["bold"] }
"markup.heading.marker"  = { fg = "blue", modifiers = ["bold"] }
"markup.list"            = "blue"
"markup.bold"            = { modifiers = ["bold"] }
"markup.italic"          = { modifiers = ["italic"] }
"markup.strikethrough"   = { modifiers = ["crossed_out"] }
"markup.link"            = "blue"
"markup.link.text"       = "orange"
"markup.quote"           = "green"
"markup.raw"             = "green"

# UI
"diff.plus"   = "green"
"diff.minus"  = "red"
"diff.delta"  = "blue"

"ui.background"             = { fg = "fg1", bg = "bg0" }
"ui.cursor"                 = { fg = "fgr", bg = "fg0" }
"ui.cursor.primary"         = { fg = "fgr", bg = "yellow" }
# "ui.cursor.primary.select"  = { fg = "fgr", bg = "red" }
# "ui.cursor.primary.insert"  = { fg = "fgr", bg = "green" }
"ui.cursor.match"           = { fg = "yellow", bg = "bg2", modifiers = ["underlined"] }
# "ui.gutter"                 = {fg = "fg1", bg = "bg1" }
"ui.linenr"                 = "fg1"
"ui.linenr.selected"        = "yellow"
"ui.statusline"             = { fg = "fg0", bg = "bg1" }
"ui.statusline.inactive"    = { fg = "fg1", bg = "bg1" }
"ui.statusline.insert"      = { fg = "fgr", bg = "green", modifiers = ["bold"] }
"ui.statusline.select"      = { fg = "fgr", bg = "orange", modifiers = ["bold"] }
"ui.statusline.normal"      = { fg = "fgr", bg = "blue", modifiers = ["bold"] }
"ui.popup"                  = { fg = "fg0", bg = "bg1" }
"ui.window"                 = { fg = "bg2", bg = "bg0" }
"ui.help"                   = { fg = "fg0", bg = "bg1" }
"ui.text"                   = "fg0"
"ui.text.focus"             = { fg = "fg0", bg = "bg1", modifiers = ["bold"] }
"ui.virtual"                = "bg2"
"ui.virtual.ruler"          = { bg = "bg2" }
"ui.virtual.indent-guide"   = "bg2"
"ui.virtual.whitespace"     = "bg2"
"ui.virtual.jump-label"     = { fg = "fgr", bg = "blue" }
"ui.menu"                   = { fg = "fg0", bg = "bg1" }
"ui.menu.selected"          = { fg = "fgr", bg = "blue" }
"ui.menu.scroll"            = { fg = "fg1", bg = "bg1" }
"ui.selection"              = { fg = "fgr", bg = "fg1" }
"ui.selection.primary"      = { fg = "fgr", bg = "blue" }
"ui.highlight"              = { bg = "bg1" }
"ui.cursorline.primary"     = { bg = "bg1" }
"ui.cursorcolumn.primary"   = { bg = "bg1" }
"ui.bufferline.background"  = { bg = "bg1" }
"ui.bufferline"             = { fg = "fg0", bg = "bg1" }
"ui.bufferline.active"      = { fg = "fgr", bg = "blue" }

"diagnostic.error"        = { underline = { color = "red", style = "curl" } }
"diagnostic.warning"      = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info"         = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint"         = { underline = { color = "blue", style = "curl" } }
"diagnostic.unnecessary"  = { underline = { color = "blue", style = "curl" } }
"diagnostic.deprecated"   = { underline = { color = "blue", style = "curl" } }

"info"     = "blue"
"hint"     = "blue"
"warning"  = "yellow"
"error"    = "red"

[palette]

red        = "#ff8692"
green      = "#88ca95"
yellow     = "#fbf6a6"
blue       = "#79c0f1"
magenta    = "#fec0f7"
cyan       = "#87f3f2"
orange     = "#ffbe8a"
light-cyan = "#c2f3f2"

# red        = "#fe93a4"
# green      = "#95cf96"
# yellow     = "#fef1a1"
# blue       = "#7ac8f5"
# magenta    = "#fac1fc"
# cyan       = "#93fef7"
# orange     = "#feb98b"
# light-cyan = "#c9faf6"

# Grays
fg0        = "#cecece"
fg1        = "#9b9b9b"
fg2        = "#b7b7b7"
fgr        = "#000000"
bg0        = "#333333"
bg1        = "#222222"
bg2        = "#444444"

# https://coolors.co/ff8692-8ed09c-fffaaa-80c7f8-fec0f7-87f3f2-ffbe8a-c9faf9
