inherits = "light"

"special" = "green"
"function" = "green"
"constant" = "red"
"type" = "orange"
"constructor" = "orange"
"string"                = "yellow"
"comment" = "blue"

[palette]
red        = "#f67400"
green      = "#1cdc9a"
yellow     = "#c9ce3b"
orange     = "#fdbc4b"
blue       = "#3daee9"
magenta    = "#FEABF2"
cyan       = "#24DFC4"

selection  = "#24ACD4"

# Grays
fg0        = "#ffffff"
fg1        = "#afafaf"
fg2        = "#8b8b8b"
fgr        = "#000000"
bg0        = "#242424"
bg1        = "#353535"
bg2        = "#595959"

# https://coolors.co/FF4D51-35D450-E9E836-5DC5F8-FEABF2-24DFC4
