# Syntax
"function"               = "paleyellow"
"special"                = "blue"

"type"                   = "orange"
"constructor"            = "orange"

"constant.numeric"       = "blue"
"constant.character"     = "blue"
"constant.builtin"       = "blue"
"keyword"                = "blue"
"label"                  = "blue"
"variable.builtin"       = "blue"
"tag"                    = "blue"
"operator"               = "blue"

"variable"               = "cyan"
"constant"               = "cyan"
"attribute"              = "cyan"
"module"                 = "cyan"
"namespace"              = "cyan"

"punctuation"            = "fg1"
"punctuation.bracket"    = "fg1"

"string"                 = "green"

"comment"                = "fg2"

"markup.heading"         = { fg = "fgh", modifiers = ["bold"] }
"markup.heading.marker"  = { fg = "blue", modifiers = ["bold"] }
"markup.list"            = "blue"
"markup.bold"            = { fg = "fgh", modifiers = ["bold"] }
"markup.italic"          = { modifiers = ["italic"] }
"markup.strikethrough"   = { modifiers = ["crossed_out"] }
"markup.link"            = "blue"
"markup.link.text"       = "orange"
"markup.quote"           = "green"
"markup.raw"             = "green"

# UI
"diff.plus"   = "green"
"diff.minus"  = "red"
"diff.delta"  = "blue"

"ui.background"             = { fg = "fg2", bg = "bg0" }
"ui.cursor"                 = { fg = "fgr", bg = "fg1" }
"ui.cursor.primary"         = { fg = "fgr", bg = "fg0" }
# "ui.cursor.primary.select"  = { fg = "fgr", bg = "red" }
# "ui.cursor.primary.insert"  = { fg = "fgr", bg = "green" }
"ui.cursor.match"           = { fg = "yellow", bg = "bg2", modifiers = ["underlined"] }
# "ui.gutter"                 = {fg = "fg2", bg = "bg1" }
"ui.linenr"                 = "fg2"
"ui.linenr.selected"        = "fg0"
"ui.statusline"             = { fg = "fg0", bg = "bg0" }
"ui.statusline.inactive"    = { fg = "fg2", bg = "bg0" }
"ui.statusline.insert"      = { fg = "fgr", bg = "green" }
"ui.statusline.select"      = { fg = "fgr", bg = "orange" }
"ui.statusline.normal"      = { fg = "fgh", bg = "bg2" }
"ui.popup"                  = { fg = "fg0", bg = "bg1" }
"ui.window"                 = { fg = "bg2", bg = "bg0" }
"ui.picker.header.column.active" = { fg = "fgr", bg = "blue" }
"ui.help"                   = { fg = "fg0", bg = "bg1" }
"ui.text"                   = "fg0"
"ui.text.directory"         = { fg = "fg2" }
"ui.text.focus"             = { fg = "fgh", bg = "bg1" }
"ui.virtual"                = "bg2"
"ui.virtual.ruler"          = { bg = "bg2" }
"ui.virtual.indent-guide"   = "bg2"
"ui.virtual.whitespace"     = "fg2"
"ui.virtual.jump-label"     = { fg = "fgh", bg = "bg2" }
"ui.menu"                   = { fg = "fg0", bg = "bg1" }
"ui.menu.selected"          = { fg = "fgh", bg = "bg2" }
"ui.menu.scroll"            = { fg = "fg2", bg = "bg1" }
"ui.selection"              = { fg = "fgr", bg = "fg2" }
"ui.selection.primary"      = { fg = "fgr", bg = "blue" }
"ui.highlight"              = { bg = "bg2" }
"ui.cursorline.primary"     = { bg = "bg1" }
"ui.cursorcolumn.primary"   = { bg = "bg1" }
"ui.bufferline.background"  = { bg = "bg0" }
"ui.bufferline"             = { fg = "fg0", bg = "bg0" }
"ui.bufferline.active"      = { fg = "fgh", bg = "bg2" }

"diagnostic.error"        = { underline = { color = "red", style = "curl" } }
"diagnostic.warning"      = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info"         = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint"         = { underline = { color = "blue", style = "curl" } }
"diagnostic.unnecessary"  = { underline = { color = "blue", style = "curl" } }
"diagnostic.deprecated"   = { underline = { color = "blue", style = "curl" } }

"info"     = "blue"
"hint"     = "blue"
"warning"  = "yellow"
"error"    = "red"

[palette]

red        = "#ff3963"
green      = "#4ac06c"
yellow     = "#fcf47e"
blue       = "#19affe"
magenta    = "#fdcbf8"
cyan       = "#9de8fe"
orange     = "#ffa659"
paleyellow = "#fdf9ba"
darkcyan   = "#3cdab4"

# Grays

fg0        = "#dedede"  # .90
fg1        = "#a4a4a4"  # .72
fg2        = "#888888"  # .63
fgh        = "#ffffff"
fgr        = "#000000"
bg0        = "#222222"  # .25
bg1        = "#111111"  # .20
bg2        = "#444444"  # .35

# https://coolors.co/ff7c8a-73cb87-fffaaa-5cbefe-fec0f7-a4f6f5-fcb67c
