# Syntax
"function"               = "blue"
"constructor"            = "blue"
"tag"                    = "blue"
"special"                = "blue"

# "string.special"         = "yellow"
# "string.regexp"          = "yellow"
# "punctuation.special"    = "yellow"

"type"                   = "magenta"
"constant"               = "red"

"namespace"              = "fg0"
"module"                 = "fg0"
"variable"               = "fg0"

"attribute"              = "fg0"
"variable.parameter"     = "fg0"
"variable.other.member"  = "fg0"
"type.parameter"         = "fg0"

"keyword"                = "fg0"
"variable.builtin"       = "fg0"
"label"                  = "fg0"

"punctuation"            = "fg1"
"operator"               = "fg1"

"string"                 = "green"

"comment"                = { fg = "fg0", bg = "attention" }

# Markup
"markup.heading"         = { fg = "fg0", modifiers = ["bold"] }
"markup.list"            = "fg0"
"markup.bold"            = { modifiers = ["bold"] }
"markup.italic"          = { modifiers = ["italic"] }
"markup.strikethrough"   = "red"
"markup.link"            = "fg1"
"markup.link.text"       = "blue"
"markup.quote"           = "magenta"
"markup.raw"             = "green"

# UI
"diff.plus"   = "green"
"diff.minus"  = "red"
"diff.delta"  = "blue"

"ui.background"             = { fg = "fg1", bg = "bg0" }
"ui.cursor"                 = { fg = "bg0", bg = "fg1" }
"ui.cursor.primary"         = { fg = "bg0", bg = "fg0" }
# "ui.cursor.primary.select"  = { fg = "bg0", bg = "red" }
# "ui.cursor.primary.insert"  = { fg = "bg0", bg = "green" }
"ui.cursor.match"           = { fg = "fg0", bg = "selection", modifiers = ["bold"] }
# "ui.gutter"                 = {fg = "fg1", bg = "bg1" }
"ui.linenr"                 = "fg2"
"ui.linenr.selected"        = "fg0"
"ui.statusline"             = { fg = "fg0", bg = "bg2" }
"ui.statusline.inactive"    = { fg = "fg1", bg = "bg2" }
"ui.statusline.insert"      = { fg = "bg0", bg = "green" }
"ui.statusline.select"      = { fg = "bg0", bg = "blue" }
"ui.statusline.normal"      = { fg = "fg0", bg = "bg2" }
"ui.popup"                  = { fg = "fg1", bg = "bg1" }
"ui.window"                 = { fg = "bg2", bg = "bg0" }
"ui.help"                   = { fg = "fg0", bg = "bg1" }
"ui.text"                   = "fg0"
"ui.text.focus"             = { fg = "fg0", bg = "bg1", modifiers = ["bold"] }
"ui.virtual"                = "fg1"
"ui.virtual.ruler"          = { bg = "bg1" }
"ui.virtual.indent-guide"   = "bg2"
"ui.virtual.whitespace"     = "bg2"
"ui.menu"                   = { fg = "fg0", bg = "bg1" }
"ui.menu.selected"          = { fg = "fg0", bg = "bg2" }
"ui.selection"              = { fg = "fg0", bg = "bg2" }
"ui.selection.primary"      = { fg = "fg0", bg = "selection" }
"ui.highlight"              = { bg = "bg2" }
"ui.cursorline.primary"     = { bg = "bg1" }
"ui.cursorcolumn.primary"   = { bg = "bg1" }
"ui.bufferline.background"  = { bg = "bg2" }
"ui.bufferline"             = { fg = "fg0", bg = "bg2" }
"ui.bufferline.active"      = { fg = "fg0", bg = "bg0" }

"diagnostic.error"    = { underline = { color = "red", style = "curl" } }
"diagnostic.warning"  = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info"     = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint"     = { underline = { color = "blue", style = "curl" } }

"info"     = "blue"
"hint"     = "blue"
"warning"  = "yellow"
"error"    = "red"

[palette]
# Colors
red        = "#eb0000"
green      = "#008800"
yellow     = "#946F00"
blue       = "#003feb"
magenta    = "#c400eb"
cyan       = "#008099"
selection  = "#6CD4FF"
attention  = "#FFEE99"

# Grays
fg0        = "#000000"
fg1        = "#747474"
fg2        = "#888888"
bg0        = "#FcFcFc"
bg1        = "#f0f0f0"
bg2        = "#d0d0d0"

# fg0        = "#232629"
# fg1        = "#7f8c8d"
# bg1        = "#eff0f1"
# bg2        = "#bdc3c7"

# https://coolors.co/d60047-0047d6-8f00d6-008080-2c8500-9e6900
