# Syntax
"function"               = "blue"
"special"                = "blue"

"type"                   = "red"
"constructor"            = "red"

"constant"               = "magenta"

"namespace"              = "fg0"
"module"                 = "fg0"
"variable"               = "fg0"

"attribute"              = "fg0"
"variable.parameter"     = "fg0"
"variable.other.member"  = "fg0"
"type.parameter"         = "fg0"

"keyword"                = "fg0"
"variable.builtin"       = "fg0"
"tag"                    = "red"
"label"                  = "fg0"

"punctuation"            = "fg1"
"operator"               = "fg1"

"string"                 = "green"

"comment"                = { fg = "fg0", bg = "attention" }

# Markup
"markup.heading"         = { fg = "fg0", modifiers = ["bold"] }
"markup.heading.marker"  = { fg = "blue", modifiers = ["bold"] }
"markup.list"            = "blue"
"markup.bold"            = { modifiers = ["bold"] }
"markup.italic"          = { modifiers = ["italic"] }
"markup.strikethrough"   = { modifiers = ["crossed_out"] }
"markup.link"            = "green"
"markup.link.text"       = "blue"
"markup.quote"           = "green"
"markup.raw"             = "green"

# UI
"diff.plus"   = "lightgreen"
"diff.minus"  = "lightred"
"diff.delta"  = "lightblue"

"ui.background"             = { fg = "fg1", bg = "bg0" }
"ui.cursor"                 = { fg = "fgr", bg = "fg1" }
"ui.cursor.primary"         = { fg = "fgr", bg = "fg0" }
# "ui.cursor.primary.select"  = { fg = "fgr", bg = "red" }
# "ui.cursor.primary.insert"  = { fg = "fgr", bg = "green" }
"ui.cursor.match"           = { fg = "fg0", bg = "bg2", modifiers = ["underlined"] }
# "ui.gutter"                 = {fg = "fg1", bg = "bg1" }
"ui.linenr"                 = "fg2"
"ui.linenr.selected"        = "fg0"
"ui.statusline"             = { fg = "fg0", bg = "bg2" }
"ui.statusline.inactive"    = { fg = "fg1", bg = "bg2" }
"ui.statusline.insert"      = { fg = "fgr", bg = "green", modifiers = ["bold"] }
"ui.statusline.select"      = { fg = "fgr", bg = "blue", modifiers = ["bold"] }
"ui.statusline.normal"      = { fg = "fgr", bg = "fg0", modifiers = ["bold"] }
"ui.popup"                  = { fg = "fg1", bg = "bg1" }
"ui.window"                 = { fg = "bg2", bg = "bg0" }
"ui.help"                   = { fg = "fg0", bg = "bg1" }
"ui.text"                   = "fg0"
"ui.text.focus"             = { fg = "fg0", bg = "bg1", modifiers = ["bold"] }
"ui.virtual"                = "fg2"
"ui.virtual.ruler"          = { bg = "bg2" }
"ui.virtual.indent-guide"   = "bg2"
"ui.virtual.whitespace"     = "bg2"
"ui.virtual.jump-label"     = { fg = "fgr", bg = "lightblue" }
"ui.menu"                   = { fg = "fg0", bg = "bg2" }
"ui.menu.selected"          = { fg = "fgr", bg = "fg0" }
"ui.menu.scroll"            = { fg = "fg1", bg = "bg2" }
"ui.selection"              = { fg = "fg0", bg = "bg2" }
"ui.selection.primary"      = { fg = "fgr", bg = "lightblue" }
"ui.highlight"              = { bg = "bg1" }
"ui.cursorline.primary"     = { bg = "bg1" }
"ui.cursorcolumn.primary"   = { bg = "bg1" }
"ui.bufferline.background"  = { bg = "bg2" }
"ui.bufferline"             = { fg = "fg0", bg = "bg2" }
"ui.bufferline.active"      = { fg = "fg0", bg = "bg0" }

"diagnostic.error"    = { underline = { color = "lightred", style = "curl" } }
"diagnostic.warning"  = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info"     = { underline = { color = "lightblue", style = "curl" } }
"diagnostic.hint"     = { underline = { color = "lightblue", style = "curl" } }

"info"     = "lightblue"
"hint"     = "lightblue"
"warning"  = "yellow"
"error"    = "lightred"

[palette]
# Colors                oklch:   Lightness  chroma  hue
# red        = "#d2393b"         # 57         19      25
# green      = "#12930f"         # 57         19      142
# yellow     = "#b98c00"         # 66         14      86
# blue       = "#0077e6"         # 57         19      255
# magenta    = "#a94abe"         # 57         19      320
# cyan       = "#00999e"         # 62         11      199

# More distinguishable blue / red / magenta

red        = "#df5102"         # 62         19      41
green      = "#129104"         # 57         19      142
yellow     = "#b0890e"         # 65         13      88
blue       = "#0a74e4"         # 57         19      256
magenta    = "#aa5dd8"         # 62         19      311
cyan       = "#04a3a8"         # 65         11      199

lightred   = "#ec5639"         # 65
lightgreen = "#38aa2f"         # 65
lightblue  = "#318dff"         # 65
attention  = "#fef2b3"         # 96         0.08    98

# Neutral

fg0        = "#242424"
fg1        = "#6d6d6d"
fg2        = "#929292"
fgr        = "#ffffff"
bg0        = "#FcFcFc"
bg1        = "#f0f0f0"
bg2        = "#d5d5d5"

# Warm

# fg0        = "#272419"
# fg1        = "#706d60"
# fg2        = "#969285"
# fgr        = "#ffffff"
# bg0        = "#fffcf1"
# bg1        = "#F4F1E4" # 0.017, 96.11
# bg2        = "#d9d5c7"

# Cool

# fg0        = "#232629"
# fg1        = "#7f8c8d"
# fg2        = "#7f8c8d"
# fgr        = "#ffffff"
# bg0        = "#FcFcFc"
# bg1        = "#eff0f1"
# bg2        = "#bdc3c7"
