# Syntax
"function"               = "magenta"
"special"                = "yellow"

"type"                   = "yellow"
"constructor"            = "yellow"
"module"                 = "yellow"
"namespace"              = "yellow"

"constant.numeric"       = "blue"
"constant.builtin"       = "blue"
"constant.character"     = "blue"
"variable.builtin"       = "blue"
"punctuation.special"    = "blue"
"tag"                    = "blue"
"keyword"                = "blue"
"label"                  = "blue"

"variable"               = "fg0"
"constant"               = "fg0"
"attribute"              = "fg0"

"punctuation"            = "fg1"
"operator"               = "fg1"
"punctuation.bracket"    = "fg1"

"string"                 = "green"

"comment"                = { fg = "fg2", modifiers = [ "italic" ] }

# Markup
"markup.heading"         = { fg = "fg0", modifiers = ["bold"] }
"markup.heading.marker"  = { fg = "blue", modifiers = ["bold"] }
"markup.list"            = "blue"
"markup.bold"            = { modifiers = ["bold"] }
"markup.italic"          = { modifiers = ["italic"] }
"markup.strikethrough"   = { modifiers = ["crossed_out"] }
"markup.link"            = "blue"
"markup.link.text"       = "yellow"
"markup.quote"           = "green"
"markup.raw"             = "green"

# UI
"diff.plus"   = "green"
"diff.minus"  = "red"
"diff.delta"  = "cyan"

"ui.background"             = { fg = "fg1", bg = "bg0" }
"ui.cursor"                 = { fg = "fgr", bg = "fg1" }
"ui.cursor.primary"         = { fg = "fgr", bg = "fg0" }
# "ui.cursor.primary.select"  = { fg = "fgr", bg = "red" }
# "ui.cursor.primary.insert"  = { fg = "fgr", bg = "green" }
"ui.cursor.match"           = { fg = "fg0", bg = "bg2", modifiers = ["underlined"] }
# "ui.gutter"                 = {fg = "fg1", bg = "bg1" }
"ui.linenr"                 = "fg2"
"ui.linenr.selected"        = "fg0"
"ui.statusline"             = { fg = "fg0", bg = "bg2" }
"ui.statusline.inactive"    = { fg = "fg1", bg = "bg2" }
"ui.statusline.insert"      = { fg = "fgr", bg = "green"  }
"ui.statusline.select"      = { fg = "fgr", bg = "yellow"  }
"ui.statusline.normal"      = { fg = "fg0", bg = "bg2"  }
"ui.popup"                  = { fg = "fg1", bg = "bg1" }
"ui.window"                 = { fg = "bg2", bg = "bg0" }
"ui.help"                   = { fg = "fg0", bg = "bg1" }
"ui.text"                   = "fg0"
"ui.text.directory"         = "blue"
"ui.text.focus"             = { fg = "fg0", bg = "bg1" }
"ui.virtual"                = "fg2"
"ui.virtual.ruler"          = { bg = "bg2" }
"ui.virtual.indent-guide"   = "bg2"
"ui.virtual.whitespace"     = "bg2"
"ui.virtual.jump-label"     = { fg = "fg0", bg = "bg2" }
"ui.menu"                   = { fg = "fg0", bg = "bg2" }
"ui.menu.selected"          = { fg = "fgr", bg = "fg2" }
"ui.menu.scroll"            = { fg = "fg1", bg = "bg2" }
"ui.selection"              = { fg = "fgr", bg = "fg2" }
"ui.selection.primary"      = { fg = "fgr", bg = "cyan" }
"ui.highlight"              = { bg = "bg1" }
"ui.cursorline.primary"     = { bg = "bg1" }
"ui.cursorcolumn.primary"   = { bg = "bg1" }
"ui.bufferline.background"  = { bg = "bg2" }
"ui.bufferline"             = { fg = "fg0", bg = "bg2" }
"ui.bufferline.active"      = { fg = "fg0", bg = "bg0" }

"diagnostic.error"        = { underline = { color = "red", style = "curl" } }
"diagnostic.warning"      = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info"         = { underline = { color = "cyan", style = "curl" } }
"diagnostic.hint"         = { underline = { color = "cyan", style = "curl" } }
"diagnostic.unnecessary"  = { underline = { color = "cyan", style = "curl" } }
"diagnostic.deprecated"   = { underline = { color = "cyan", style = "curl" } }

"info"     = "cyan"
"hint"     = "cyan"
"warning"  = "yellow"
"error"    = "red"

[palette]

# red        = "#ac001e"
# green      = "#02910e"
# yellow     = "#ce3d02"
# blue       = "#0251c2"
# magenta    = "#994ec9"
# cyan       = "#4087fd"

red        = "#d02c2e"
green      = "#01a233"
yellow     = "#f15a0a"
blue       = "#335cdb"
magenta    = "#9565f0"
cyan       = "#2f84ff"

attention  = "#fef1a1"

# Neutral

fg0        = "#444444"
fg1        = "#686868"
fg2        = "#949494"
fgr        = "#ffffff"
bg0        = "#ffffff"
bg1        = "#f3f3f3"
bg2        = "#e8e8e8"

# Warm

# fg0        = "#272419"
# fg1        = "#706d60"
# fg2        = "#969285"
# fgr        = "#ffffff"
# bg0        = "#fffcf1"
# bg1        = "#F4F1E4" # 0.017, 96.11
# bg2        = "#d9d5c7"

# Cool

# fg0        = "#232629"
# fg1        = "#7f8c8d"
# fg2        = "#7f8c8d"
# fgr        = "#ffffff"
# bg0        = "#FcFcFc"
# bg1        = "#eff0f1"
# bg2        = "#bdc3c7"
