# Syntax
"function"               = "blue"
"special"                = "blue"

"type"                   = "magenta"
"constructor"            = "magenta"

"constant.builtin"       = "red"
"constant.numeric"       = "red"
"constant.character"     = "red"

"namespace"              = "fg0"
"module"                 = "fg0"
"variable"               = "fg0"

"attribute"              = "fg0"
"variable.parameter"     = "fg0"
"variable.other.member"  = "fg0"
"type.parameter"         = "fg0"

"keyword"                = "fg0"
"variable.builtin"       = "fg0"
"tag"                    = "fg0"
"label"                  = "fg0"

"punctuation"            = "fg1"
"operator"               = "fg1"

"string"                 = "green"

"comment"                = { fg = "fg0", bg = "attention" }

# Markup
"markup.heading"         = { fg = "fg0", modifiers = ["bold"] }
"markup.list"            = "fg0"
"markup.bold"            = { modifiers = ["bold"] }
"markup.italic"          = { modifiers = ["italic"] }
"markup.strikethrough"   = { modifiers = ["crossed_out"] }
"markup.link"            = "magenta"
"markup.link.text"       = "blue"
"markup.quote"           = "green"
"markup.raw"             = "green"

# UI
"diff.plus"   = "green"
"diff.minus"  = "red"
"diff.delta"  = "blue"

"ui.background"             = { fg = "fg1", bg = "bg0" }
"ui.cursor"                 = { fg = "fgr", bg = "fg1" }
"ui.cursor.primary"         = { fg = "fgr", bg = "fg0" }
# "ui.cursor.primary.select"  = { fg = "fgr", bg = "red" }
# "ui.cursor.primary.insert"  = { fg = "fgr", bg = "green" }
"ui.cursor.match"           = { fg = "fg0", bg = "bg2", modifiers = ["underlined"] }
# "ui.gutter"                 = {fg = "fg1", bg = "bg1" }
"ui.linenr"                 = "fg2"
"ui.linenr.selected"        = "fg0"
"ui.statusline"             = { fg = "fg0", bg = "bg2" }
"ui.statusline.inactive"    = { fg = "fg1", bg = "bg2", modifiers = ["bold"] }
"ui.statusline.insert"      = { fg = "fgr", bg = "green", modifiers = ["bold"] }
"ui.statusline.select"      = { fg = "fgr", bg = "blue", modifiers = ["bold"] }
"ui.statusline.normal"      = { fg = "fgr", bg = "fg0", modifiers = ["bold"] }
"ui.popup"                  = { fg = "fg1", bg = "bg1" }
"ui.window"                 = { fg = "bg2", bg = "bg0" }
"ui.help"                   = { fg = "fg0", bg = "bg1" }
"ui.text"                   = "fg0"
"ui.text.focus"             = { fg = "fg0", bg = "bg1", modifiers = ["bold"] }
"ui.virtual"                = "fg2"
"ui.virtual.ruler"          = { bg = "bg2" }
"ui.virtual.indent-guide"   = "bg2"
"ui.virtual.whitespace"     = "bg2"
"ui.menu"                   = { fg = "fg0", bg = "bg2" }
"ui.menu.selected"          = { fg = "fgr", bg = "fg1" }
"ui.menu.scroll"            = { fg = "fg1", bg = "bg2" }
"ui.selection"              = { fg = "fg0", bg = "bg2" }
"ui.selection.primary"      = { fg = "fgr", bg = "selection" }
"ui.highlight"              = { bg = "bg1" }
"ui.cursorline.primary"     = { bg = "bg1" }
"ui.cursorcolumn.primary"   = { bg = "bg1" }
"ui.bufferline.background"  = { bg = "bg2" }
"ui.bufferline"             = { fg = "fg0", bg = "bg2" }
"ui.bufferline.active"      = { fg = "fg0", bg = "bg0" }

"diagnostic.error"    = { underline = { color = "red", style = "curl" } }
"diagnostic.warning"  = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info"     = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint"     = { underline = { color = "blue", style = "curl" } }

"info"     = "blue"
"hint"     = "blue"
"warning"  = "yellow"
"error"    = "red"

[palette]
# Colors                oklch:   Lightness  chroma  hue
red        = "#d2393b"         # 57         19      25
green      = "#12930f"         # 57         19      142
yellow     = "#ac8200"         # 63         13      86
blue       = "#0077e6"         # 57         19      255
magenta    = "#a94abe"         # 57         19      320
cyan       = "#008e92"         # 58         10      199

selection  = "#258afb"         # 63         19      255
attention  = "#FFF2B3"         # 96         0.08    98

# Grays
fg0        = "#242424"
fg1        = "#6d6d6d"
fg2        = "#8a8a8a"
fgr        = "#ffffff"
bg0        = "#FcFcFc"
bg1        = "#f0f0f0"
bg2        = "#d5d5d5"

# fg0        = "#232629"
# fg1        = "#7f8c8d"
# fg2        = "#7f8c8d"
# fgr        = "#ffffff"
# bg0        = "#FcFcFc"
# bg1        = "#eff0f1"
# bg2        = "#bdc3c7"
