"function"               = "magenta"
"special"                = "magenta"
"constructor"            = "blue"
"type"                   = "blue"
"constant"               = "cyan"
"string"                 = "green"
"punctuation"            = "fg1"
"operator"               = "fg1"
"comment"                = "yellow"

"markup.heading"         = { fg = "fgh", modifiers = ["bold"] }
"markup.list"            = "fg1"
"markup.bold"            = { modifiers = ["bold"] }
"markup.italic"          = { modifiers = ["italic"] }
"markup.strikethrough"   = { modifiers = ["crossed_out"] }
"markup.link"            = "magenta"
"markup.link.text"       = "blue"
"markup.quote"           = "green"
"markup.raw"             = "green"

"diff.plus"   = { fg = "green", bg = "bg0" }
"diff.minus"  = { fg = "red", bg = "bg0" }
"diff.delta"  = { fg = "blue", bg = "bg0" }

"ui.background"             = { fg = "fg2", bg = "bg0" }
"ui.cursor"                 = { fg = "fgr", bg = "fg1" }
"ui.cursor.primary"         = { fg = "fgr", bg = "yellow" }
"ui.cursor.match"           = { fg = "yellow", bg = "bg2", modifiers = ["underlined"] }
"ui.linenr"                 = "fg2"
"ui.linenr.selected"        = "yellow"
"ui.statusline"             = { fg = "fg0", bg = "bg2" }
"ui.statusline.inactive"    = { fg = "fg2", bg = "bg0" }
"ui.statusline.insert"      = { fg = "fgr", bg = "green" }
"ui.statusline.select"      = { fg = "fgr", bg = "blue" }
"ui.statusline.normal"      = { fg = "fgr", bg = "yellow" }
"ui.popup"                  = { fg = "fg1", bg = "bg1" }
"ui.window"                 = { fg = "bg2", bg = "bg0" }
"ui.help"                   = { fg = "fg0", bg = "bg1" }
"ui.text"                   = "fg0"
"ui.text.focus"             = { fg = "fgh", bg = "bg1" }
"ui.virtual"                = "fg1"
"ui.virtual.ruler"          = { bg = "bg2" }
"ui.virtual.indent-guide"   = "bg2"
"ui.virtual.whitespace"     = "bg2"
"ui.menu"                   = { fg = "fg0", bg = "bg2" }
"ui.menu.selected"          = { fg = "fgr", bg = "yellow" }
"ui.selection"              = { fg = "fgr", bg = "fg2" }
"ui.selection.primary"      = { fg = "fgr", bg = "selection" }
"ui.highlight"              = { bg = "bg2" }
"ui.cursorline.primary"     = { bg = "bg1" }
"ui.cursorcolumn.primary"   = { bg = "bg1" }
"ui.bufferline.background"  = { bg = "bg2" }
"ui.bufferline"             = { fg = "fg0", bg = "bg2" }
"ui.bufferline.active"      = { fg = "fgr", bg = "yellow" }

"diagnostic.error"    = { underline = { color = "red", style = "curl" } }
"diagnostic.warning"  = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info"     = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint"     = { underline = { color = "blue", style = "curl" } }

"info"     = "blue"
"hint"     = "blue"
"warning"  = "yellow"
"error"    = "red"

[palette]
red        = "#FF4D51"
green      = "#35D450"
yellow     = "#E9E836"
blue       = "#5DC5F8"
magenta    = "#FEABF2"
cyan       = "#24DFC4"

selection  = "#24ACD4"

# Grays
fg0        = "#ffffff"
fg1        = "#afafaf"
fg2        = "#8b8b8b"
fgr        = "#000000"
fgh        = "#ffffff"
bg0        = "#242424"
bg1        = "#353535"
bg2        = "#4a4a4a"

# https://coolors.co/FF4D51-35D450-E9E836-5DC5F8-FEABF2-24DFC4
