inherits = "dark"


"function"               = "gray"

"type"                   = "orange"
"constructor"            = "orange"

"constant"               = "magenta"
"constant.numeric"       = "magenta"
"constant.builtin"       = "magenta"
"constant.character"     = "magenta"

"namespace"              = "fg0"
"module"                 = "fg0"
"variable"               = "fg0"
"attribute"              = "fg0"
"variable.parameter"     = "fg0"
"variable.other.member"  = "fg0"

"keyword"                = "red"
"variable.builtin"       = "red"
"label"                  = "red"
"special"                = "red"
"tag"                    = "red"

"punctuation"            = "fg1"
"operator"               = "fg1"
"punctuation.bracket"    = "fg1"

"string"                 = "blue"

"comment"                = "green"


[palette]
red        = "#F08868"
green      = "#95E095"
orange     = "#F0A858"
yellow     = "#F0E070"
sand       = "#E0C888"
blue       = "#7DC6E0"
dark-blue  = "#80B0B8"
magenta    = "#F0C6F0"
cyan       = "#9DE7F0"
gray       = "#B0C8D0"
dark-gray  = "#A8B8D0"

# fg0        = "#E8F0F0"


