inherits = "starlight"


"function"               = "white"
"constructor"            = "white"

"type"                   = "yellow"
"string.special"         = "yellow"
"string.regexp"          = "yellow"
"constant"               = "yellow"
"punctuation.special"    = "yellow"

"namespace"              = "green"
"module"                 = "green"
"variable"               = "green"

"attribute"              = "cyan"
"variable.parameter"     = "cyan"
"variable.other.member"  = "cyan"
"type.parameter"         = "cyan"

"keyword"                = "red"
"variable.builtin"       = "red"
"label"                  = "red"
"tag"                    = "red"
"operator"               = "red"
"special"                = "red"

"string"                 = "sand"

"punctuation"            = "punct"

"comment"                = "dark-fg"


[palette]
red        = "#F08048"
green      = "#8FA775"
yellow     = "#F0A858"
sand       = "#E0C888"
blue       = "#48B0E8"
dark-blue  = "#1098E0"
magenta    = "#B09890"
cyan       = "#90E0B0"
white      = "#ffffff"
punct      = "#C9C9C9"

# Grays
black      = "#1e1e1e"
dark-bg    = "#242424"
medium-bg  = "#2D2D2D"
light-bg   = "#353535"
indent     = "#616161"
dark-fg    = "#929292"
light-fg   = "#E6E6E6"
