inherits = "dark"


"function"               = "gray"

"type"                   = "orange"
"constructor"            = "orange"
"namespace"              = "orange"
"module"                 = "orange"

"constant"               = "fg0"
"constant.numeric"       = "green"
"constant.builtin"       = "green"
"constant.character"     = "green"

"variable"               = "fg0"
"attribute"              = "fg0"
"variable.parameter"     = "fg0"
"variable.other.member"  = "fg0"

"keyword"                = "red"
"variable.builtin"       = "red"
"label"                  = "red"
"special"                = "red"
"tag"                    = "red"

"punctuation"            = "fg1"
"operator"               = "fg1"
"punctuation.bracket"    = "fg1"

"string"                 = "blue"

"comment"                = "dark-gray"


[palette]
red        = "#F08868"
green      = "#BAF0B2"
orange     = "#F0B880"
yellow     = "#F0C800"
sand       = "#E0C888"
blue       = "#7DC6E0"
dark-blue  = "#80B0B8"
magenta    = "#F0C7F0"
cyan       = "#78C8E8"
dark-cyan  = "#78A8B8"
gray       = "#B0C8D0"
dark-green = "#789820"
dark-gray  = "#58B088"

fg1       = "#B0C8D0"
fg2       = "#688088"

# fg0        = "#E8F0F0"


