# Syntax highlighting
# -------------------
# Green for things that do stuff (functions).
"function" = "green"

# Cold for things that are stuff and often stay constant. Also constructors to differentiate them from functions.
"type" = "cyan"
"constructor" = "cyan"
"namespace" = "cyan"
"module" = "cyan"
"constant" = "blue"
"string" = "dark-cyan"

# Warm colors for things that are stuff but often don't stay constant
"variable" = "sand"
"attribute" = "yellow"
"variable.parameter" = "yellow"
"variable.other.member" = "yellow"

# Orange for keywords, language-specific stuff and operators
"keyword" = "orange"
"variable.builtin" = "orange"
"label" = "orange"
"tag" = "orange"
"operator" = "orange"

# Dark punctuation and comments
"punctuation" = "rock"
"comment" = { fg = "dark-fg", modifiers = ["italic"] }


# Markup and other non-syntax stuff
# ---------------------------------------
"special" = "white" # fuzzy highlight

"markup.heading.marker" = { fg = "orange", modifiers = ["bold"] }
"markup.heading" = { fg = "sand", modifiers = ["bold"] }
"markup.list" = "orange"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "yellow", modifiers = ["italic"] }
"markup.link.url" = { fg = "dark-cyan", modifiers = ["underlined"] }
"markup.link.text" = "cyan"
"markup.quote" = "green"
"markup.raw" = "green"

"diff.plus" = "green"
"diff.delta" = "blue"
"diff.minus" = "red"

# User Interface
# --------------
"ui.background" = { fg = "dark-fg", bg = "dark-bg" }

"ui.linenr" = { fg = "dark-fg" }
"ui.linenr.selected" = { fg = "dark-yellow", bg = "faint-hl" }

"ui.statusline" = { fg = "white", bg = "light-bg" }
"ui.statusline.inactive" = { fg = "dark-fg", bg = "faint-hl" }
"ui.statusline.normal" = { fg = "dark-bg", bg = "dark-cyan", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "dark-bg", bg = "green", modifiers = ["bold"]  }
"ui.statusline.select" = { fg = "dark-bg", bg = "orange", modifiers = ["bold"]  }

"ui.bufferline.background" = { bg = "dark-bg" }
"ui.bufferline" = { fg = "light-fg", bg = "dark-bg" }
"ui.bufferline.active" = { fg = "white", bg = "light-bg" }

# hover
"ui.popup" = { fg = "light-fg", bg = "light-bg" }
# whichkey
"ui.popup.info" = { fg = "light-fg", bg = "faint-hl" }
# splits
"ui.window" = { fg = "light-bg", bg = "dark-bg" }
# command description
"ui.help" = { fg = "light-fg", bg = "faint-hl" }

# base text (including markdown)
"ui.text" = "light-fg"
# picker hl
"ui.text.focus" = { fg = "dark-bg", bg = "orange" }

"ui.virtual" = "dark-fg"
"ui.virtual.ruler" = "dark-fg"
"ui.virtual.indent-guide" = "light-bg"
"ui.virtual.whitespace" = "light-fg"

"ui.selection" = { fg = "light-fg", bg = "light-bg" }
"ui.selection.primary" = { fg = "white", bg = "dark-blue" }

"ui.cursor" = { fg = "dark-bg", bg = "light-fg" }
"ui.cursor.match" = { fg = "blue", bg = "light-bg", modifiers = ["underlined", "bold"] }
"ui.cursor.primary" = { fg = "dark-bg", bg = "dark-yellow" }

"ui.cursorline" = { bg = "faint-hl" }

"ui.highlight" = { bg = "light-bg" }

"ui.menu" = { fg = "light-fg", bg = "light-bg" }
"ui.menu.selected" = { fg = "dark-bg", bg = "orange" }

"info" = "blue"
"hint" = "green"
"warning" = "dark-yellow"
"error" = "red"
"diagnostic.info".underline = { color = "blue", style = "curl" }
"diagnostic.hint".underline = { color = "green", style = "curl" }
"diagnostic.warning".underline = { color = "dark-yellow", style = "curl" }
"diagnostic.error".underline = { color = "red", style = "curl" }

[palette]
# Grays
dark-bg        = "#1E1E1E"
faint-hl       = "#282828"
light-bg       = "#404040"
dark-fg        = "#6E6E6E"
light-fg       = "#BBBBBB"
white          = "#E6E6E6"

# Syntax colors
green          = "#93B649"
cyan           = "#A2DEB4"
dark-cyan      = "#5E9689"
blue           = "#5BAEEA"
dark-blue      = "#285577"
yellow         = "#FFDE82"
dark-yellow    = "#F0B858"
orange         = "#DA7E42"
sand           = "#F1ECCE"
rock           = "#8FA096"
red            = "#FE5F55"

# Palette:
# https://coolors.co/5e9689-5baeea-A2DEB4-93b649-da7e42-ffde82-f1ecce
