# Syntax
# ----------------------------------------------------
# Green for things that do stuff (functions).
"function" = "green"

# Cold colors for things that are stuff and often stay constant.
# Also constructors to differentiate them from functions.
"type" = "cyan"
"constructor" = "cyan"
"namespace" = "cyan"
"module" = "cyan"
"constant" = "blue"
"string" = "dark-cyan"

# light warm colors for things that are stuff but often don't stay constant
"variable" = "sand"
"attribute" = "yellow"
"variable.parameter" = "yellow"
"variable.other.member" = "yellow"

# Orange for keywords, language-specific stuff and operators
"keyword" = "orange"
"variable.builtin" = "orange"
"label" = "orange"
"tag" = "orange"
"operator" = "orange"

# Dark punctuation and comments
"punctuation" = "rock"
"comment" = { fg = "medium-fg", modifiers = ["italic"] }


# UI, markup, other non-syntax stuff
# ----------------------------------------------------
"special" = "orange" # fuzzy highlight

"markup.heading.marker" = { fg = "orange", modifiers = ["bold"] }
"markup.heading" = { fg = "sand", modifiers = ["bold"] }
"markup.list" = "orange"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "yellow", modifiers = ["italic"] }
"markup.link.url" = "dark-cyan"
"markup.link.text" = "cyan"
"markup.quote" = "green"
"markup.raw" = "green"

"diff.plus" = "green"
"diff.delta" = "blue"
"diff.minus" = "red"

# User Interface
# --------------
"ui.background" = { fg = "dark-fg", bg = "dark-bg" }

"ui.linenr" = { fg = "dark-fg" }
"ui.linenr.selected" = "dark-yellow"

"ui.statusline" = { fg = "light-fg", bg = "light-bg" }
"ui.statusline.inactive" = { fg = "dark-fg", bg = "light-bg" }
"ui.statusline.normal" = { fg = "medium-fg", bg = "light-bg" }
"ui.statusline.insert" = { fg = "black", bg = "green" }
"ui.statusline.select" = { fg = "black", bg = "orange" }

"ui.bufferline.background" = { bg = "dark-bg" }
"ui.bufferline" = { fg = "light-fg", bg = "light-bg" }
"ui.bufferline.active" = { fg = "white", bg = "dark-fg" }

# hover
"ui.popup" = { fg = "light-fg", bg = "light-bg" }
# menus
"ui.menu" = { fg = "light-fg", bg = "light-bg" }
"ui.menu.selected" = { fg = "white", bg = "dark-fg", modifiers = ["bold"] }
# command description
"ui.help" = { fg = "light-fg", bg = "light-bg" }
# splits
"ui.window" = { fg = "light-bg", bg = "dark-bg" }

# base text (including markdown)
"ui.text" = "light-fg"
# picker hl
"ui.text.focus" = { fg = "white", bg = "light-bg", modifiers = ["bold"] }

"ui.virtual" = "dark-fg"
"ui.virtual.ruler" = { bg = "medium-bg" }
"ui.virtual.indent-guide" = "indent"

"ui.cursorline.primary" = { bg = "black" }
"ui.cursorcolumn.primary" = { bg = "black" }

# selections & cursors
"ui.selection.primary" = { fg = "white", bg = "dark-blue" }
"ui.selection" = { fg = "light-fg", bg = "dark-fg" }

"ui.cursor.primary" = { fg = "black", bg = "dark-yellow" }
"ui.cursor.primary.select" = { fg = "black", bg = "orange" }
"ui.cursor.primary.insert" = { fg = "black", bg = "green" }
"ui.cursor" = { fg = "black", bg = "light-fg" }
"ui.cursor.match" = { fg = "blue", bg = "light-bg", modifiers = ["bold"] }

"ui.highlight" = { bg = "light-bg" }

"info" = "blue"
"hint" = "blue"
"warning" = "dark-yellow"
"error" = "red"
"diagnostic" = "blue"
"diagnostic.info" = "blue"
"diagnostic.hint" = "blue"
"diagnostic.warning" = "dark-yellow"
"diagnostic.error" = "red"


[palette]

# Syntax colors (don't use / use sparingly in the UI)
# ----------------------------------------------------
green          = "#88B830"  # function
cyan           = "#A2DEB4"  # type, namespace
dark-cyan      = "#489888"  # string
blue           = "#30B0F0"  # const
yellow         = "#FFDE82"  # parameter
orange         = "#F09038"  # keyword
sand           = "#FDF6E3"  # variable
rock           = "#8FA096"  # punctuation

# UI
# ----------------------------------------------------
# Grays dark to bright
black          = "#1e1e1e"  # black text, cursorline
dark-bg        = "#242424"  # base background
medium-bg      = "#303030"  # rulers
light-bg       = "#353535"  # menu / popup bg
indent         = "#404040"  # menu / popup bg
dark-fg        = "#6A6A6A"  # barely legible text
medium-fg      = "#939393"  # low prio text
light-fg       = "#E6E6E6"  # normal / bright text
white          = "#FFFFFF"  # very bright text

# colors (non-syntax)
dark-blue      = "#007888"  # text selection
dark-yellow    = "#F0B858"  # primary cursor, warnings
red            = "#FE5F55"  # error, deletion

# Preview (syntax colors only)
# ----------------------------------------------------
# https://coolors.co/f09038-88b830-fdf6e3-ffde82-a2deb4-489888-30b0f0-8fa096-404040
