inherits = "celadon"


"ui.cursor" = { fg = "dark-bg", bg = "dark-fg" }
"ui.cursor.primary" = { fg = "dark-bg", bg = "dark-yellow" }
"ui.cursor.match" = { fg = "white", bg = "light-bg", modifiers = ["underlined", "bold"] }

"ui.bufferline.background" = { bg = "dark-bg" }
"ui.bufferline" = { fg = "light-fg", bg = "light-bg" }
"ui.bufferline.active" = { fg = "dark-bg", bg = "light-fg" }

"ui.statusline" = { fg = "light-fg", bg = "light-bg" }
"ui.statusline.inactive" = { fg = "dark-fg", bg = "light-bg" }
"ui.statusline.normal" = { fg = "dark-bg", bg = "rock", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "dark-bg", bg = "green", modifiers = ["bold"]  }
"ui.statusline.select" = { fg = "dark-bg", bg = "orange", modifiers = ["bold"]  }

# whichkey
"ui.popup.info" = { fg = "light-fg", bg = "dark-bg" }
# command description
"ui.help" = { fg = "light-fg", bg = "dark-bg" }

# hover
"ui.menu" = { fg = "light-fg", bg = "light-bg" }
"ui.menu.selected" = { fg = "dark-bg", bg = "light-fg" }

# diff
"diff.plus" = "light-green"
"diff.delta" = "light-blue"

[palette]
# Grays
dark-bg        = "#FDF6E3"
faint-hl       = "#FEFBF1"
light-bg       = "#EEE8D5"
dark-fg        = "#B2B29A"
light-fg       = "#6E6E6E"
white          = "#404040"

# Syntax colors
green          = "#78A828"
cyan           = "#0090A8"
dark-cyan      = "#489888"
blue           = "#4070B0"
dark-blue      = "#F0B858"
selection      = "#D0DFCD"
yellow         = "#827CDF"
dark-yellow    = "#6e6e6e"
orange         = "#D85808"
sand           = "#404040"
rock           = "#8FA096"
red            = "#FE5F55"

# gutter
light-blue     = "#57A7D8"
light-green    = "#88B830"
