[language-server.ruff-lsp]
command = "ruff-lsp"

[language-server.ltex-ls]  # get this from aur
command = "ltex-ls"
config = { ltex.language = "en-GB" }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
language-servers = ["pyright", "ruff-lsp"]
formatter = { command = "black", args = ["--quiet", "-"] }

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "latex"
file-types = ["tex", "sty"]
language-servers = ["texlab", "ltex-ls"]

[[language]]
name = "typst"
language-servers = ["typst-lsp"]

[[language]]
name = "markdown"
file-types = ["md"]
language-servers = ["ltex-ls"]
formatter = { command = 'mdformat', args = ["--wrap", "80", "-"] }
auto-format = true
