[language-server.ruff]
command = "uvx"
args = ["ruff", "server"]

[language-server.ltex-ls]  # get this from aur
command = "ltex-ls"
config = { ltex.language = "en-GB" }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
language-servers = ["pyright"]
# formatter = { command = "black", args = ["--quiet", "-"] }
formatter = { command = "uvx", args = ["ruff", "format", "-"] }
auto-format = true

[[language]]
name = "c"
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = "npx", args = ["prettier", "--parser", "json"] }

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "/usr/lib/node_modules/typescript/lib" }}

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls"]
formatter = { command = "npx", args = ["prettier", "--plugin", "prettier-plugin-astro", "--parser", "astro"] }
auto-format = true

[[language]]
name = "tsx"
file-types = ["tsx"]
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "latex"
file-types = ["tex", "sty"]
language-servers = ["texlab", "ltex-ls"]

[[language]]
name = "typst"
language-servers = ["typst-lsp"]

[[language]]
name = "markdown"
file-types = ["md", "rmd", "Rmd"]
# language-servers = ["ltex-ls"]
formatter = { command = "uvx", args = ["mdformat", "--wrap", "80", "-"] }
auto-format = true
