[language-server.ruff]
command = "uvx"
args = ["ruff", "server"]

[language-server.ltex-ls]  # get this from aur
command = "ltex-ls"
config = { ltex.language = "en-US" }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
language-servers = ["pyright"]
# formatter = { command = "black", args = ["--quiet", "-"] }
formatter = { command = "uvx", args = ["ruff", "format", "-"] }
auto-format = true

[[language]]
name = "sql"
language-servers = ["postgrestools"]

[language-server.postgrestools]
command = "postgrestools"
args = ["lsp-proxy"]
# config = { typescript = { tsdk = "/usr/lib/node_modules/typescript/lib" }}

[[language]]
name = "c"
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = "npx", args = ["prettier", "--parser", "json"] }

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "/usr/lib/node_modules/typescript/lib" }}

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls"]
formatter = { command = "npx", args = ["prettier", "--plugin", "prettier-plugin-astro", "--parser", "astro"] }
auto-format = true

[[language]]
name = "tsx"
file-types = ["tsx"]
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "latex"
file-types = ["tex", "sty"]
language-servers = ["texlab", "ltex-ls"]


[language-server.tinymist]
command = "tinymist"

[[language]]
name = "typst"
language-servers = ["tinymist"]

[[language]]
name = "markdown"
file-types = ["md", "rmd", "Rmd"]
language-servers = ["marksman", "ltex-ls"]
# formatter = { command = "uvx", args = ["--from", "mdformat-tables", "mdformat", "--wrap", "80", "-"] }
formatter = { command = "uvx", args = ["mdformat", "--wrap", "80", "-"] }
auto-format = true

[[language]]
name = "xml"
file-types = [
  "xml",
  "mobileconfig",
  "plist",
  "xib",
  "storyboard",
  "svg",
  "xsd",
  "gml",
  "xaml",
  "gir",
  "rss",
  "atom",
  "opml",
  "policy",
  "ascx",
  "axml",
  "axaml",
  "bpmn",
  "cpt",
  "csl",
  "csproj.user",
  "dita",
  "ditamap",
  "dtml",
  "fxml",
  "iml",
  "isml",
  "jmx",
  "launch",
  "menu",
  "mxml",
  "nuspec",
  "osc",
  "osm",
  "pt",
  "publishsettings",
  "pubxml",
  "pubxml.user",
  "rbxlx",
  "rbxmx",
  "rng",
  "shproj",
  "tld",
  "tmx",
  "vbproj.user",
  "vcxproj",
  "vcxproj.filters",
  "wsdl",
  "wxi",
  "wxs",
  "xbl",
  "xlf",
  "xliff",
  "xpdl",
  "xul",
  "xoml",
  "musicxml",
  "glif",
  "ui",
  "sublime-snippet",
  "xsl",
  "mpd",
  "smil",
  "qgs",
  "sld",
  "qml",
]

[[language]]
name = "ini"
file-types = [
  "ini",
  "desktop",
  { glob = "mimeapps.list" },
  # Podman quadlets
  "container",
  "volume",
  "kube",
  "network",
  { glob = ".editorconfig" },
  { glob = ".npmrc" },
  { glob = "hgrc" },
  { glob = "npmrc" },
  { glob = "rclone.conf" },
  "properties",
  "cfg",
  "directory",
  "conf"
]
