[character]
success_symbol = "[](bold purple)"
error_symbol = "[](bold bright-red)"

[package]
disabled = true
# style = "bold green"

[directory]
format = "[ $path]($style)[$read_only]($read_only_style) "
style = "bold cyan"
truncation_length = 2

[container]
disabled = true

# [git_state]
# style = "bold blue"
# [git_status]
# style = "bold blue"
# [git_branch]
# style = "bold purple"
