definitions:
  fonts:
    - font: &font-default monospace:semibold:pixelsize=14
    - font: &font-bold monospace:bold:pixelsize=14
  colors:
    - color: &color-good 89d298ff
    - color: &color-urgent ff0000ff
    - color: &color-focus 285577ff
    - color: &color-fade 868a8cff
    - color: &color-bg 202224ff
    - color: &color-fg ffffffff
    - color: &color-fgh ffffffff
    - color: &color-fgr 000000ff

bar:
  height: 20
  location: top
  background: *color-bg
  foreground: *color-fg
  font: *font-default

  left:
    - i3:
        content:
          current:
            string:
              text: "{name} "
              max: 80
    - i3:
        content:
          "":  # catch-all to map to every workspace
            map:
              conditions:
                urgent:
                  string:
                    text: " Go to: {name} "
                    on-click: "swaymsg --quiet workspace {name}"
                    foreground: *color-fgh
                    font: *font-bold
                    deco: {background: {color: *color-urgent}}

    - i3:
        content:
          "":
            map:
              conditions:
                mode != "default" && focused:
                  string:
                    text: " {mode} "
                    foreground: *color-fgh
                    font: *font-bold
                    deco: {background: {color: *color-focus}}

  right:

    - battery:
        name: BAT0
        poll-interval: 30000
        content:
          map:
            conditions:
              state == "unknown":
                - string: {text: "", foreground: *color-good}
              state != "charging":
                ramp:
                  tag: capacity
                  items:
                    - string:
                        text: " BATTERY LOW {capacity}% "
                        foreground: *color-fgh
                        font: *font-bold
                        deco: {background: {color: *color-urgent}}
                    - string: {text: " Battery {capacity}% "}
                    - string: {text: " Battery {capacity}% "}
                    - string: {text: " Battery {capacity}% "}
              state == "charging":
                - string:
                    text: " Battery {capacity}% (charging) "
                    foreground: *color-good
                    # deco: {background: {color: *color-focus}}

    - network:
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlp3s0:
                map:
                  default:
                    string: {text: " Wifi {quality}% "}
                  conditions:
                    state == "up":
                      string: {text: " Wifi {quality}% "}
                    state == "down":
                      string: {text: " Wifi {state} "}

    - pulse:
        content:
          map:
            on-click: /bin/sh -c "pavucontrol"
            conditions:
              ~sink_muted:
                string: {text: " {sink_port} {sink_percent}% "}
              sink_muted:
                string: {text: " {sink_port} {sink_percent}% ", foreground: *color-fade}

    - script:
        path: /home/eemil/dotfiles/confs/.config/yambar/do-not-disturb.sh
        args: []
        poll-interval: 5000
        content:
          map:
            conditions:
              state == "on":
                string:
                  text: " Do not disturb "
                  on-click: "/home/eemil/dotfiles/confs/.config/yambar/do-not-disturb.sh toggle"
              state == "off":
                string:
                  text: " Do not disturb "
                  on-click: "/home/eemil/dotfiles/confs/.config/yambar/do-not-disturb.sh toggle"
                  foreground: *color-fade

    # - pipewire:
    #     content:
    #       map:
    #         on-click: /bin/sh -c "pavucontrol"
    #         conditions:
    #           ~muted:
    #             string: {text: "{form_factor} {cubic_volume}%", margin: *margin-default}
    #           muted:
    #             string: {text: "{form_factor} {cubic_volume}%", margin: *margin-default, foreground: 888888ff}

    - clock:
        content:
          - string: {text: " {time}"}
