bar:
  height: 20
  location: top
  background: 282828ff
  foreground: f0f0f0ff
  font: monospace:pixelsize=14

  left:
    - i3:
        content:
          "":
            map:
              default: {string: {text: "({name}) "}}
              conditions:
                ~focused:
                  string: {text: ""}
                mode != "default":
                  string: {text: "{mode} ({name}) "}
          current: { string: {text: "{title}", max: 80}}

  right:
    - battery:
        name: BAT0
        poll-interval: 30000
        content:
          map:
            conditions:
              state != "charging":
                ramp:
                  tag: capacity
                  items:
                    - string: {text: "Battery {capacity}%", margin: 10, foreground: ff5050ff}
                    - string: {text: "Battery {capacity}%", margin: 10}
                    - string: {text: "Battery {capacity}%", margin: 10}
                    - string: {text: "Battery {capacity}%", margin: 10}
              state == "charging":
                - string: {text: "Battery {capacity}% (charging)", foreground: 00ff00ff}

    - network:
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlp3s0:
                map:
                  default:
                    string: {text: "Wifi {quality}%", margin: 10}
                  conditions:
                    state == "up":
                      string: {text: "Wifi {quality}%", margin: 10}
                    state == "down":
                      string: {text: "Wifi {state}", margin: 10}

    - pipewire:
        content:
          map:
            on-click: /bin/sh -c "pavucontrol"
            conditions:
              ~muted:
                string: {text: "Volume ({form_factor}) {cubic_volume}%", margin: 10}
              muted:
                string: {text: "Volume ({form_factor}) {cubic_volume}%", margin: 10, foreground: 888888ff}

    - clock:
        content:
          - string: {text: "{time}", left-margin: 10}
