definitions:
  fonts:
    - font: &font-default monospace:semibold:pixelsize=14
    - font: &font-bold monospace:bold:pixelsize=14
  colors:
    - color: &color-good 35D450ff
    - color: &color-urgent FF4D51ff
    - color: &color-fade 888888ff
  margins:
    - margin: &margin-default 15

bar:
  height: 20
  location: top
  background: 222222ff
  foreground: ffffffff
  font: *font-default

  left:
    - i3:
        content:
          "":
            map:
              default: {string: {text: ""}}
              conditions:
                focused:
                  string: {text: "{name} "}
                urgent:
                  string: {text: "{name} ", on-click: "swaymsg --quiet workspace {name}", foreground: *color-urgent, font: *font-bold}
          current:
            map:
              conditions:
                mode != "default":
                  string: {text: "({mode}) "}


  right:
    - battery:
        name: BAT0
        poll-interval: 30000
        content:
          map:
            conditions:
              state != "charging":
                ramp:
                  tag: capacity
                  items:
                    - string: {text: "BATTERY LOW {capacity}%", margin: *margin-default, foreground: *color-urgent, font: *font-bold}
                    - string: {text: "Battery {capacity}%", margin: *margin-default}
                    - string: {text: "Battery {capacity}%", margin: *margin-default}
                    - string: {text: "Battery {capacity}%", margin: *margin-default}
              state == "charging":
                - string: {text: "Battery {capacity}% (charging)", margin: *margin-default, foreground: *color-good}

    - network:
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlp3s0:
                map:
                  default:
                    string: {text: "Wifi {quality}%", margin: *margin-default}
                  conditions:
                    state == "up":
                      string: {text: "Wifi {quality}%", margin: *margin-default}
                    state == "down":
                      string: {text: "Wifi {state}", margin: *margin-default}

    - pulse:
        content:
          map:
            on-click: /bin/sh -c "pavucontrol"
            conditions:
              ~sink_muted:
                string: {text: "{sink_port} {sink_percent}%", margin: *margin-default}
              sink_muted:
                string: {text: "{sink_port} {sink_percent}%", margin: *margin-default, foreground: *color-fade}

    # - pipewire:
    #     content:
    #       map:
    #         on-click: /bin/sh -c "pavucontrol"
    #         conditions:
    #           ~muted:
    #             string: {text: "{form_factor} {cubic_volume}%", margin: *margin-default}
    #           muted:
    #             string: {text: "{form_factor} {cubic_volume}%", margin: *margin-default, foreground: 888888ff}

    - clock:
        content:
          - string: {text: "{time}", left-margin: *margin-default}
