[language-server.ruff-lsp]
command = "ruff-lsp"

[[language]]
name = "python"
language-servers = ["pyright", "ruff-lsp"]
formatter = { command = "black", args = ["--quiet", "-"] }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "latex"
file-types = ["tex", "sty"]
